version: '2'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest 
    container_name: db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=zbklomfps%23%uitr
    ports:
      - "1433:1433"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    environment:
      - DOTNET_ConnectionStrings__Blanche=Server=db,1433;Initial Catalog=blanche;User Id=sa;Password=MyStrongPassword123%;Encrypt=True;TrustServerCertificate=True;
      - DOTNET_ENVIRONMENT=Production
      - DOTNET_LocalDbPassword=zbklomfps%23%uitr
    ports:
        - "80:80"

 


