using Blanche.Shared.Customers;
using Riok.Mapperly.Abstractions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.ConstrainedExecution;
using System.Text;
using System.Threading.Tasks;

namespace Blanche.Domain.Customers.Mappers
{
    [Mapper]
    public partial class AddressMapper
    {
       
        private partial Address MapToAddress(AddressDto addressDto);

        public partial Address MapAddressDtoToAddress(AddressDto addressDto);
        //{
        //    // The autogenerated file could not be generated for unkown reason
             
        //    return Address.Builder()
        //        .WithStreet(addressDto.Street)
        //        .WithNumber(addressDto.HouseNumber)
        //        .WithCity(addressDto.City)
        //        .WithPostalCode(addressDto.PostalCode)
        //        .WithCountry(addressDto.Country)
        //        .Build();
        //}

      

        
    }
}
